name = "EasyEvents"
uuid = "1c3e8eab-fb9d-4faa-86a4-2d4d6165c1a6"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]
version = "0.1.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
